services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./deploy/dev/dockerfile.frontend # 路径小错，改为 deploy
  #   container_name: edupal_frontend_dev
  #   working_dir: /app
  #   command: ["pnpm", "dev"] # 如果你已经改用 pnpm
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules # 防止主机和容器的 node_modules 冲突
  #   ports:
  #     - "5173:5173"

  backend:
    build:
      context: backend
      dockerfile: ../deploy/prod/dockerfile.backend
    container_name: edupal_backend_dev
    ports:
      - "8000:80"
    volumes:
      - ./backend/app:/app/app
