version: '3.9'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ../deploy/dev/dockerfile.frontend
  #   container_name: edupal_frontend_dev
  #   working_dir: /app
  #   command: ["pnpm", "dev"]
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules  # 防止主机和容器的 node_modules 冲突
  #   ports:
  #     - "5173:5173"  # 前端开发端口
  #   restart: always

  backend:
    build:
      context: backend
      dockerfile: ../deploy/dev/dockerfile.backend
    container_name: edupal_backend_dev
    command:
      [
        "/app/.venv/bin/uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]
    environment:
      - SECRET_KEY=your-secret-key
      - EXPIRE_DAYS=7
      - DATABASE_URL=mysql+pymysql://edupal:edupal@mysql:3306/edupal
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - api_key=your_api_key
      - base_url=http://localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - mysql
      - rabbitmq
    restart: on-failure

  # agent:
  #   build:
  #     context: agent
  #     dockerfile: ../deploy/dev/dockerfile.agent
  #   container_name: edupal_agent_dev
  #   command: ["go", "run", "main.go"]
  #   environment:
  #     - DATABASE_URL=edupal:edupal@tcp(mysql:3306)/edupal?charset=utf8mb4&parseTime=True&loc=Local
  #     - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
  #     - api_key=your_api_key
  #     - base_url=http://localhost:8000
  #   volumes:
  #     - ./agent:/app
  #   depends_on:
  #     - mysql
  #     - rabbitmq
  #   restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: edupal_mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: edupal
      MYSQL_PASSWORD: edupal
      MYSQL_DATABASE: edupal
      TZ: Asia/Shanghai
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: edupal_rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "15672:15672"  # 管理页面端口
      - "5672:5672"    # 消息队列通信端口
    restart: always

volumes:
  mysql_data:
