FROM python:3.12-slim

# 安装 uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# 将应用程序复制到容器中
COPY . /app

# 安装应用程序依赖
WORKDIR /app
RUN uv sync --frozen --no-cache

# 运行应用程序（注意这里使用 uvicorn）
CMD ["/app/.venv/bin/uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
