// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuestiontrace = "questiontrace"

// Questiontrace mapped from table <questiontrace>
type Questiontrace struct {
	CreatedAt  time.Time      `gorm:"column:created_at;type:datetime;not null" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	IsDeleted  bool           `gorm:"column:is_deleted;type:tinyint(1);not null" json:"is_deleted"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:datetime" json:"deleted_at"`
	ID         int32          `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	UserID     int32          `gorm:"column:user_id;type:int;not null" json:"user_id"`
	QuestionID int32          `gorm:"column:question_id;type:int;not null" json:"question_id"`
	Source     string         `gorm:"column:source;type:varchar(255);not null" json:"source"`
	Model      string         `gorm:"column:model;type:varchar(255)" json:"model"`
	SourceID   string         `gorm:"column:source_id;type:varchar(255)" json:"source_id"`
}

// TableName Questiontrace's table name
func (*Questiontrace) TableName() string {
	return TableNameQuestiontrace
}
