package mysql

import (
	"agent/dal/model"
	"log"
	"time"
)

func insertInitialQuestions() {
	if err := DB.Create(&InitialQuestions).Error; err != nil {
		log.Fatalf("插入初始化数据失败: %v", err)
	}
	log.Println("初始化题目数据成功")
}

var InitialQuestions = []model.Question{
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "五年级",
		Difficulty:  "简单",
		Type:        "选择题",
		Content:     "5 × 6 等于多少？",
		Options:     "A.30;B.11;C.60;D.26",
		Answer:      "A",
		Explanation: "乘法口诀：五六三十。",
		IsPublic:    true,
		Tag:         "乘法",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "三年级",
		Difficulty:  "简单",
		Type:        "填空题",
		Content:     "“百尺竿头，更进一步”这句话比喻什么？",
		Options:     "",
		Answer:      "已经很好了还要更上一层楼",
		Explanation: "鼓励人不断进取。",
		IsPublic:    true,
		Tag:         "成语",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "六年级",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "一个圆的半径是5厘米，那么它的直径是10厘米。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "直径等于半径的两倍，5 × 2 = 10。",
		IsPublic:    true,
		Tag:         "几何",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "四年级",
		Difficulty:  "中等",
		Type:        "计算题",
		Content:     "一个苹果2元，小明买了3个苹果和1个5元的面包，一共花了多少钱？",
		Options:     "",
		Answer:      "11",
		Explanation: "2 × 3 + 5 = 11。",
		IsPublic:    true,
		Tag:         "应用题",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "四年级",
		Difficulty:  "简单",
		Type:        "判断题",
		Content:     "“亡羊补牢”这个成语的意思是事情出了问题再去补救也不迟。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "意思是出了问题后及时补救，可以防止继续受损。",
		IsPublic:    true,
		Tag:         "成语",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "英语",
		Grade:       "五年级",
		Difficulty:  "简单",
		Type:        "选择题",
		Content:     "What is the plural of 'apple'?",
		Options:     "A.apples;B.applees;C.appls;D.apple",
		Answer:      "A",
		Explanation: "名词apple复数加-s为apples。",
		IsPublic:    true,
		Tag:         "语法",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "历史",
		Grade:       "初一",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "秦始皇统一中国是在公元前___年。",
		Options:     "",
		Answer:      "221",
		Explanation: "公元前221年秦始皇完成统一。",
		IsPublic:    true,
		Tag:         "中国古代史",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "物理",
		Grade:       "初二",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "水在常压下的沸点是100℃。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "标准大气压下，水在100℃时沸腾。",
		IsPublic:    true,
		Tag:         "热学",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "地理",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "世界上面积最大的大洲是？",
		Options:     "A.非洲;B.亚洲;C.美洲;D.欧洲",
		Answer:      "B",
		Explanation: "亚洲是世界上面积最大的洲。",
		IsPublic:    true,
		Tag:         "世界地理",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "化学",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "水的化学式是______。",
		Options:     "",
		Answer:      "H2O",
		Explanation: "水由两个氢原子和一个氧原子组成。",
		IsPublic:    true,
		Tag:         "基础化学",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "生物",
		Grade:       "初二",
		Difficulty:  "简单",
		Type:        "判断题",
		Content:     "植物进行光合作用需要阳光。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "光合作用的必要条件之一是光照。",
		IsPublic:    true,
		Tag:         "植物",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "高二",
		Difficulty:  "中等",
		Type:        "计算题",
		Content:     "解方程：2x - 3 = 7。",
		Options:     "",
		Answer:      "x = 5",
		Explanation: "2x = 10，所以x = 5。",
		IsPublic:    true,
		Tag:         "代数",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "政治",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "宪法的根本特点是？",
		Options:     "A.灵活性;B.权威性;C.详细性;D.地域性",
		Answer:      "B",
		Explanation: "宪法是国家的根本大法，具有最高法律效力。",
		IsPublic:    true,
		Tag:         "法治",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "“会当凌绝顶，_____。”出自杜甫的《望岳》。",
		Options:     "",
		Answer:      "一览众山小",
		Explanation: "这是杜甫诗中的名句，表达豪情壮志。",
		IsPublic:    true,
		Tag:         "古诗词",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "三年级",
		Difficulty:  "简单",
		Type:        "判断题",
		Content:     "一个正方形的四条边长度都相等。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "正方形定义就是四边相等。",
		IsPublic:    true,
		Tag:         "图形与几何",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "英语",
		Grade:       "初一",
		Difficulty:  "简单",
		Type:        "选择题",
		Content:     "Which one is a fruit?",
		Options:     "A.chair;B.apple;C.table;D.car",
		Answer:      "B",
		Explanation: "apple 是水果，其他选项不是。",
		IsPublic:    true,
		Tag:         "词汇",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "物理",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "力的三要素是：力的大小、方向和______。",
		Options:     "",
		Answer:      "作用点",
		Explanation: "力的三要素决定了力的效果。",
		IsPublic:    true,
		Tag:         "力学基础",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "化学",
		Grade:       "高二",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "酸碱中和反应一定放热。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "酸碱反应是一种放热反应。",
		IsPublic:    true,
		Tag:         "酸碱盐",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "六年级",
		Difficulty:  "简单",
		Type:        "填空题",
		Content:     "“桃李满天下”形容的是______多。",
		Options:     "",
		Answer:      "学生",
		Explanation: "比喻老师教出的学生很多、很优秀。",
		IsPublic:    true,
		Tag:         "成语理解",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "历史",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "新文化运动的核心人物是？",
		Options:     "A.鲁迅;B.李大钊;C.陈独秀;D.蔡元培",
		Answer:      "C",
		Explanation: "陈独秀是新文化运动的主要发起人之一。",
		IsPublic:    true,
		Tag:         "近代中国",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "地理",
		Grade:       "初一",
		Difficulty:  "简单",
		Type:        "判断题",
		Content:     "赤道穿过中国大陆。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "赤道穿过的是东南亚、非洲等地，不经过中国。",
		IsPublic:    true,
		Tag:         "地理常识",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "计算题",
		Content:     "一个几何体的底面积为10cm²，高为6cm，体积是多少？",
		Options:     "",
		Answer:      "60cm³",
		Explanation: "体积 = 底面积 × 高，10 × 6 = 60。",
		IsPublic:    true,
		Tag:         "几何体积",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "政治",
		Grade:       "高二",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "我国国家机构的组织原则是？",
		Options:     "A.法制统一;B.民主集中制;C.依法治国;D.人民当家作主",
		Answer:      "B",
		Explanation: "国家机构的组织原则是民主集中制。",
		IsPublic:    true,
		Tag:         "国家制度",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "英语",
		Grade:       "初二",
		Difficulty:  "简单",
		Type:        "填空题",
		Content:     "He ______ to school every day by bike.",
		Options:     "",
		Answer:      "goes",
		Explanation: "第三人称单数一般现在时动词加-s。",
		IsPublic:    true,
		Tag:         "时态",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "二年级",
		Difficulty:  "简单",
		Type:        "填空题",
		Content:     "7 加上 8 等于（   ）。",
		Options:     "",
		Answer:      "15",
		Explanation: "7 + 8 = 15。",
		IsPublic:    true,
		Tag:         "加法",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "五年级",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "“洛阳纸贵”这个成语是形容？",
		Options:     "A.物价上涨;B.文章非常流行;C.纸张短缺;D.人丁兴旺",
		Answer:      "B",
		Explanation: "比喻作品广受欢迎，争相传阅。",
		IsPublic:    true,
		Tag:         "成语理解",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "生物",
		Grade:       "初一",
		Difficulty:  "简单",
		Type:        "判断题",
		Content:     "病毒可以在离开宿主后独立生存。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "病毒必须依附在宿主细胞中才能生存和繁殖。",
		IsPublic:    true,
		Tag:         "病毒知识",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "历史",
		Grade:       "高二",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "辛亥革命爆发于公元_____年。",
		Options:     "",
		Answer:      "1911",
		Explanation: "1911年，孙中山领导的辛亥革命推翻了清朝统治。",
		IsPublic:    true,
		Tag:         "近代史",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "物理",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "下列哪种现象是光的反射？",
		Options:     "A.彩虹;B.镜子中的像;C.凸透镜成像;D.日食",
		Answer:      "B",
		Explanation: "镜子中的像是光的反射现象。",
		IsPublic:    true,
		Tag:         "光学",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "化学",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "金属都能与盐酸反应生成氢气。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "并非所有金属都能与盐酸反应，如铜等不能。",
		IsPublic:    true,
		Tag:         "金属反应",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "地理",
		Grade:       "初一",
		Difficulty:  "简单",
		Type:        "填空题",
		Content:     "黄河发源于我国的______省。",
		Options:     "",
		Answer:      "青海",
		Explanation: "黄河发源于青藏高原的巴颜喀拉山。",
		IsPublic:    true,
		Tag:         "中国地理",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "计算题",
		Content:     "若 a = 3, b = 4, 求 √(a² + b²) 的值。",
		Options:     "",
		Answer:      "5",
		Explanation: "√(9 + 16) = √25 = 5。",
		IsPublic:    true,
		Tag:         "勾股定理",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "政治",
		Grade:       "初二",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "社会主义的根本任务是解放和发展社会生产力。",
		Options:     "正确;错误",
		Answer:      "正确",
		Explanation: "发展生产力是社会主义制度优越性的体现。",
		IsPublic:    true,
		Tag:         "政治常识",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "英语",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "Which of the following is the correct past tense of 'go'?",
		Options:     "A.goed;B.went;C.going;D.gone",
		Answer:      "B",
		Explanation: "'go' 的过去式是 'went'，属于不规则变化。",
		IsPublic:    true,
		Tag:         "时态语法",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "初三",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "《岳阳楼记》中，范仲淹借洞庭湖水势变化描绘官员的心态，并提出“先天下之忧而忧，后天下之乐而乐”的主张，这句话体现了哪种精神？",
		Options:     "A.个人英雄主义;B.功利主义;C.忧国忧民、以天下为己任的精神;D.避世隐居的精神",
		Answer:      "C",
		Explanation: "该名句体现了古代士人关心国家、胸怀天下的情怀。",
		IsPublic:    true,
		Tag:         "古文理解",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "历史",
		Grade:       "高一",
		Difficulty:  "较难",
		Type:        "填空题",
		Content:     "1921年，中国共产党在上海召开第一次全国代表大会，标志着中国历史进入新的阶段。这次会议后来转移到浙江嘉兴的一艘游船上继续召开，这艘船被称为“______”。",
		Options:     "",
		Answer:      "红船",
		Explanation: "“红船”象征中国共产党开天辟地的大事变，具有重要历史意义。",
		IsPublic:    true,
		Tag:         "近代中国",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "数学",
		Grade:       "高三",
		Difficulty:  "较难",
		Type:        "计算题",
		Content:     "已知函数 f(x) = 2x² - 4x + 1，求它在区间 [1, 3] 上的最大值和最小值，并写出对应的 x 值。",
		Options:     "",
		Answer:      "最小值为 -1, 当 x = 1；最大值为 7, 当 x = 3",
		Explanation: "通过求导 f'(x)=4x-4，得极值点 x=1，结合端点值计算可得答案。",
		IsPublic:    true,
		Tag:         "函数极值",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "物理",
		Grade:       "高二",
		Difficulty:  "较难",
		Type:        "判断题",
		Content:     "物体在水平面上做匀加速直线运动，如果忽略摩擦力作用，那么只要速度不断增加，加速度就一定也在增加。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "加速度是速度变化的快慢，不随速度大小变化；匀加速运动中，加速度是恒定的。",
		IsPublic:    true,
		Tag:         "运动学",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "化学",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "选择题",
		Content:     "将一小块金属钠投入盛有水的烧杯中，观察到金属迅速游动，并产生气泡，最终溶液呈碱性。这一反应的生成物不包括下列哪项？",
		Options:     "A.NaOH;B.H2;C.NaCl;D.热量",
		Answer:      "C",
		Explanation: "Na + H2O → NaOH + H2↑，没有生成 NaCl。",
		IsPublic:    true,
		Tag:         "金属与水反应",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "地理",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "判断题",
		Content:     "地球自转是地球围绕太阳公转的基础，因此白天黑夜交替是由地球公转引起的。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "白天黑夜交替是地球**自转**造成的，而不是公转。",
		IsPublic:    true,
		Tag:         "地理基础知识",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "英语",
		Grade:       "高二",
		Difficulty:  "较难",
		Type:        "选择题",
		Content:     "Despite the bad weather, the team decided to go ahead with the plan, _____ they knew the risk was high.",
		Options:     "A.though;B.because;C.since;D.unless",
		Answer:      "A",
		Explanation: "尽管他们知道风险很大，但还是执行计划，“though”表示转折关系。",
		IsPublic:    true,
		Tag:         "语法逻辑",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "生物",
		Grade:       "高一",
		Difficulty:  "中等",
		Type:        "填空题",
		Content:     "光合作用的本质是将______能转化为______能。",
		Options:     "",
		Answer:      "光能，化学能",
		Explanation: "植物通过光合作用将光能转化为储存在葡萄糖中的化学能。",
		IsPublic:    true,
		Tag:         "光合作用",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "政治",
		Grade:       "高二",
		Difficulty:  "较难",
		Type:        "判断题",
		Content:     "依法治国的核心是依法行政，根本目的是建设法治政府，实现经济发展。",
		Options:     "正确;错误",
		Answer:      "错误",
		Explanation: "依法治国的核心是依宪治国，建设法治国家，依法行政只是其中之一。",
		IsPublic:    true,
		Tag:         "宪法与法律",
		SourceID:    "init",
	},
	{
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		IsDeleted:   false,
		UserID:      1,
		Subject:     "语文",
		Grade:       "高中",
		Difficulty:  "较难",
		Type:        "填空题",
		Content:     "《出师表》中，诸葛亮自陈“受任于败军之际，奉命于危难之间”，展现了他什么样的精神风貌？请简要填入成语。",
		Options:     "",
		Answer:      "忠诚担当",
		Explanation: "诸葛亮在国家危难时挺身而出，体现出忠心耿耿、勇于担责的精神。",
		IsPublic:    true,
		Tag:         "古文主旨",
		SourceID:    "init",
	},
}
